### ISSUE TITLE
图片为什么是竖着的？

### ISSUE THREAD

**Issue by kingfly0927** [JLinMr/PixPro#1]
![PixPin_2024-08-03_11-17-41](https://github.com/user-attachments/assets/b80301ce-f9c1-40ea-bebf-da4a6fedfe35)
就这样

**Comment by kingfly0927** [comment]
怎么能让它横着？

**Comment by kingfly0927** [comment]
我传到你的那个图床然后后台也是这样横图变成竖着的了

**Comment by kingfly0927** [comment]
另外PNG格式的图片会404
![PixPin_2024-08-03_12-06-34](https://github.com/user-attachments/assets/be892ad9-1653-4044-910c-f635bb30990f)
下面的是我的png图片
![photo1(1)](https://github.com/user-attachments/assets/ab3e4ade-1f21-4ea4-92c1-7b13fc907bb3)

**Comment by kingfly0927** [comment]
1.那个图片颠倒好像是我图片尺寸顺序读取错误（没问题了哈哈哈）
2.就是那个png图片上传404问题（没解决）

**Comment by JLinMr** [comment]
> 就是那个png图片上传404问题（没解决）

能否发个链接呢，我上传显示一切正常的

https://i1.wp.com/dev.ruom.top/i/2024/08/07/355809.webp

**Comment by JLinMr** [comment]
> 1.那个图片颠倒好像是我图片尺寸顺序读取错误（没问题了哈哈哈） 2.就是那个png图片上传404问题（没解决）

还有你好像用的不是我的这个程序吧

**Comment by kingfly0927** [comment]
一样的，你这个我部署了也是一样的，后来我看问题都一样，就没部署了

**Comment by kingfly0927** [comment]
有一个程序和你的差不多

**Comment by kingfly0927** [comment]
那个叫minipix程序，我以为你们一起的

**Comment by kingfly0927** [comment]
这个背景图是我换的

**Comment by JLinMr** [comment]
> 这个背景图是我换的

能否提供一下出现问题的图片呢

**Comment by kingfly0927** [comment]
![test](https://github.com/user-attachments/assets/24be05d6-2c68-4c93-a60f-978e2e7894d8)
图还是这个图，刚刚我重新部署了，图可以显示上传了，但是png格式不压缩
![Uploading PixPin_2024-08-07_14-37-42.jpg…]()

**Comment by JLinMr** [comment]
你说的横图变竖图也是这个吗

https://i1.wp.com/dev.ruom.top/i/2024/08/07/355809.webp
你发的这个图压缩后是可以获取信息的 你可以自行查看https://dev.ruom.top/admin/
![image](https://github.com/user-attachments/assets/a77fa541-9fe3-42b5-8d16-de1f34788d16)

QQ: 153336174 可以联系一下，看一下具体的错误日志和信息

**Comment by kingfly0927** [comment]
![PixPin_2024-08-07_14-47-05](https://github.com/user-attachments/assets/c43933f7-aacd-4398-8417-8ae7f5f8ddb6)
 添加了，确实没压缩，那个横图竖图那个是我的图片问题，横竖的尺寸读取错误，现在就是png不压缩

**Comment by Xinslive** [comment]
不对劲，png按理来说是可以压缩的

**Comment by JLinMr** [comment]
> ![PixPin_2024-08-07_14-47-05](https://private-user-images.githubusercontent.com/111177332/355704999-c43933f7-aacd-4398-8417-8ae7f5f8ddb6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTM2MzMsIm5iZiI6MTcyMzAxMzMzMywicGF0aCI6Ii8xMTExNzczMzIvMzU1NzA0OTk5LWM0MzkzM2Y3LWFhY2QtNDM5OC04NDE3LThhZTdmNWY4ZGRiNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwNjQ4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjk1OTJlYzM2ZmYzZWFiNmZkYzI2ZTJiNTA3MWNjM2YyM2FjYjJjYjhiNjVhODY2NGViN2FjYzE5NGRjOTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RUlf5xQpmn2xdfSzgJSCLnlnbRLvDTh9BHqbwCm6wmA) 添加了，确实没压缩，那个横图竖图那个是我的图片问题，横竖的尺寸读取错误，现在就是png不压缩

你好。并没有收到你的好友申请，麻烦你留一下你的联系方式吧

**Comment by kingfly0927** [comment]
qq2811297368

**Comment by JLinMr** [comment]
无法复现此问题，附一个临时解决方案: 

修改`config/image_processing.php`

头部添加以下代码
```php
/**
 * 使用Imagick将PNG图片转换为JPEG格式
 */
function convertPngToJpegWithImagick($source, $destination, $quality = 60) {
    try {
        $image = new Imagick($source);
        $image->setImageFormat('jpeg');
        $image->setImageCompressionQuality($quality);
        $image->setImageAlphaChannel(Imagick::ALPHACHANNEL_DEACTIVATE);
        $image = $image->mergeImageLayers(Imagick::LAYERMETHOD_FLATTEN);
        $width = $image->getImageWidth();
        $height = $image->getImageHeight();
        $maxWidth = 2500;
        $maxHeight = 1600;
        if ($width > $maxWidth || $height > $maxHeight) {
            $ratio = min($maxWidth / $width, $maxHeight / $height);
            $newWidth = round($width * $ratio);
            $newHeight = round($height * $ratio);
            $image->resizeImage($newWidth, $newHeight, Imagick::FILTER_LANCZOS, 1);
        }
        $result = $image->writeImage($destination);
        $image->clear();
        $image->destroy();
        return $result;
    } catch (Exception $e) {
        logMessage('Imagick转换PNG为JPEG失败: ' . $e->getMessage());
        return false;
    }
}
```

![image_processing.php](https://github.com/user-attachments/assets/16f9b8a0-7ed5-472c-8d35-16d809dc8035)
