### ISSUE TITLE
后台多模式预览，多用户

### ISSUE THREAD

**Issue by IkiiNet** [JLinMr/PixPro#12]
如果后台能多模式预览就好了，列表 缩略图 瀑布流等，现在就是瀑布流的话后台进去后显示感觉特别乱。

另外如果能加入多用户的功能就好了，这样就可以团队使用了。

**Comment by abloom25** [comment]
对，也希望可以加入相册功能，先star了，等功能完善了把兰空换了

**Comment by JLinMr** [comment]
> 如果后台能多模式预览就好了，列表 缩略图 瀑布流等，现在就是瀑布流的话后台进去后显示感觉特别乱。
> 
> 另外如果能加入多用户的功能就好了，这样就可以团队使用了。


关于多用户功能，只需要稍微修改一下就能实现了，登录用户上传是会记录上传用户id的，改一下后台的查询逻辑就可以了，再简单添加一个注册表单就好了
![image](https://github.com/user-attachments/assets/1e453424-4062-4b13-b5ea-78b092e8b861)

抱歉，我未来不会准备添加多用户功能，项目初衷就是一个个人使用的项目，如果需要团队协作推荐使用兰空图床，本项目不会添加太多功能

**Comment by IkiiNet** [comment]
奈何自己代码盲，不会。
那就自己用，感觉兰空没这个简单，就喜欢这种简单的。

**Comment by abloom25** [comment]
可以试试photoprism，挺不错的，可能会符合你的需求。
就是注意一下不要忘记关掉地图，中国版图不对。

**Comment by JLinMr** [comment]
> 可以试试photoprism，挺不错的，可能会符合你的需求。 就是注意一下不要忘记关掉地图，中国版图不对。

谢谢你的推荐

**Comment by abloom25** [comment]
没事哈哈，
但是你做的也很好。
