### ISSUE TITLE
前端跟后台背景图看上去有些问题，没有铺满页面的。

### ISSUE THREAD

**Issue by i-iooi-i** [JLinMr/PixPro#14]
![image](https://github.com/user-attachments/assets/90238fa7-a711-446d-ac50-3544c8ad22da)
![image](https://github.com/user-attachments/assets/643b6f56-fc6c-4f3a-8604-3c63d6496731)

- 前端跟后端背景图看上去有些问题，没有铺满页面的。
- 会不会考虑未来出Docker版本鸭，很想在NAS里面部署的。 🙈

**Comment by JLinMr** [comment]
你是否开了什么浏览器美化插件？
另外本项目是在16.1寸的笔记本上开发的，如果缩放有问题建议调整一下浏览器缩放比例

关于Docker版本，我有机会尝试一下吧

**Comment by JLinMr** [comment]
你是否开了什么浏览器美化插件？
另外本项目是在16.1寸的笔记本上开发的，如果缩放有问题建议调整一下浏览器缩放比例

关于Docker版本，我有机会尝试一下吧

**Comment by JLinMr** [comment]
另外我觉得应该是你的浏览器对一些css样式不兼容。

**Comment by i-iooi-i** [comment]
> 另外我觉得应该是你的浏览器对一些css样式不兼容。

![image](https://github.com/user-attachments/assets/0287f75e-cf2c-4e30-9520-45914a2a1264)

感谢大佬回复。

来家里用自己的台式机，开启访客模式，在没有各种chrome插件的情况下，背景图确实自适应，没问题的。

估计是我chrome浏览器哪一款插件导致的问题。😂

**Comment by JLinMr** [comment]
好的，没问题就好
