### ISSUE TITLE
大佬，啥时候考虑搞docker镜像啊

### ISSUE THREAD

**Issue by chenryace** [JLinMr/PixPro#17]
确实不错，不过要想火还缺个docker部署，毕竟大家都懒得部署环境。
到时候自来水帮你推。
CF搞不了吧，php太多依赖只能小鸡跑了。

**Comment by JLinMr** [comment]
我试了一下，搞不会docker，我并非专业开发者

**Comment by JLinMr** [comment]
如果有人会的话，欢迎提交Pr
