### ISSUE TITLE
大佬能支持一下又怕云嘛

### ISSUE THREAD

**Issue by lingran10** [JLinMr/PixPro#18]
喜欢用又怕云的oss，能添加一下嘛

**Comment by JLinMr** [comment]
Dev分支支持了又拍云，但是可能会有未知问题，安装了旧版本的需要重新安装
https://github.com/JLinMr/PixPro/tree/dev

**Comment by JLinMr** [comment]
数据库的结构也需要更新一下
```
ALTER TABLE images
MODIFY COLUMN storage VARCHAR(50) NOT NULL COMMENT '存储方式';
```

![image](https://github.com/user-attachments/assets/82213c44-1816-4991-ae76-6b057c847393)
