### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by luoben4040** [JLinMr/PixPro#3]
1、PNG图片上传后，好奇怪
有些png上传后无任何返回，不能出来图片地址；
有些png不转换webp，还是png （小体积的？）

2、前台上传没判断文件类型（希望判断下mime类型）
任意文件都会执行上传，只是转换失败而已。

3、这么让图片地址和web地址分离?
比如web端是www.x.com,图片地址是img.b.com？

**Comment by JLinMr** [comment]
> 1、PNG图片上传后，好奇怪 有些png上传后无任何返回，不能出来图片地址； 有些png不转换webp，还是png （小体积的？）
> 
> 2、前台上传没判断文件类型（希望判断下mime类型） 任意文件都会执行上传，只是转换失败而已。
> 
> 3、这么让图片地址和web地址分离? 比如web端是www.x.com,图片地址是img.b.com？

1.麻烦提供一下问题图片原件
2.后续版本会优化此问题
3.如果是本地存储则可以修改config/Upload_processing.php,第158行，其他存储在自定义域名设置即可

```php
$fileUrl = $protocol . 'img.xxx.com' . '/' . $uploadDirWithDatePath . basename($finalFilePath);
```

img.xxx.com 为你的域名，输出格式如下
> http://img.xxx.com/i/2024/08/10/254915.webp
