### ISSUE TITLE
Request for future support of AVIF image format.

### ISSUE THREAD

**Issue by zining3235** [JLinMr/PixPro#6]
Hi there! Could you please add support for AVIF image format? The compression rate of AVIF is great for photos. 😄

**Comment by JLinMr** [comment]
Hello! Thanks for the suggestion. While AVIF offers excellent compression rates, it's true that its compatibility across browsers and devices is still evolving. As of now, AVIF is supported by some modern browsers like Chrome and Firefox, but not by all. We need to consider broader compatibility to ensure a smooth user experience for everyone.

We'll keep an eye on the adoption and compatibility of AVIF and consider adding support in the future when it becomes more widely supported. In the meantime, we'll continue to support formats that have broader compatibility to ensure everyone can enjoy the content without issues.

Thanks for understanding! 😊

**Comment by zining3235** [comment]
Thank you for your response, looking forward to its growth.😍
