### ISSUE TITLE
The photo uploaded via iPhone was vertically rotated after compression.

### ISSUE THREAD

**Issue by zining3235** [JLinMr/PixPro#7]
![IMG_9797](https://github.com/user-attachments/assets/0a460f2b-5120-452c-8a49-04eae0c6ebdb)
![IMG_9796](https://github.com/user-attachments/assets/f219fd01-2d98-4b87-af7d-f57098539534)

**Comment by Xinslive** [comment]
Can this happen on any image? Or is it just happening in one image?

**Comment by zining3235** [comment]
Very unfortunately, it is all of them.

![IMG_9798](https://github.com/user-attachments/assets/29a50818-b14c-427b-8a1c-c894805d47a8)

**Comment by zining3235** [comment]
I tested it again. It seems that when taking a photo with the phone in landscape mode, if the camera is on the right side, the photo turns out normal. However, if the camera is on the left side, the previous issue occurs.

**Comment by JLinMr** [comment]
Could you please provide the original image of the issue that has occurred, so that I can fix the problem?

**Comment by zining3235** [comment]
[归档.zip](https://github.com/user-attachments/files/16845457/default.zip)
Of course, the images named 9872 and 9873 in the attached zip file are identical, and the images 9874 and 9875 are also identical.

**Comment by JLinMr** [comment]
Thank you for your reply, but I'm sorry to inform you that the HEIC file format you sent is not supported by the program.
